[2025-09-24T00:29:23.744+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-24T00:29:23.766+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WorkOrders.run_main manual__2025-09-24T00:29:22.083401+00:00 [queued]>
[2025-09-24T00:29:23.772+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WorkOrders.run_main manual__2025-09-24T00:29:22.083401+00:00 [queued]>
[2025-09-24T00:29:23.773+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-09-24T00:29:23.785+0000] {taskinstance.py:2907} INFO - Executing <Task(_PythonDecoratedOperator): run_main> on 2025-09-24 00:29:22.083401+00:00
[2025-09-24T00:29:23.794+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-24T00:29:23.797+0000] {standard_task_runner.py:72} INFO - Started process 255 to run task
[2025-09-24T00:29:23.797+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'WorkOrders', 'run_main', 'manual__2025-09-24T00:29:22.083401+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Example.py', '--cfg-path', '/tmp/tmp0azbfo6m']
[2025-09-24T00:29:23.799+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run_main
[2025-09-24T00:29:23.862+0000] {task_command.py:467} INFO - Running <TaskInstance: WorkOrders.run_main manual__2025-09-24T00:29:22.083401+00:00 [running]> on host 591fe0d14fa4
[2025-09-24T00:29:23.943+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WorkOrders' AIRFLOW_CTX_TASK_ID='run_main' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T00:29:22.083401+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-24T00:29:22.083401+00:00'
[2025-09-24T00:29:23.946+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-09-24T00:29:27.318+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 327, in run_main
    main()  # executa seu fluxo exatamente como está definido acima
    ^^^^^^
  File "/opt/airflow/dags/Example.py", line 294, in main
    df = filter_existing(df)
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 205, in filter_existing
    svc = get_sheets_service()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 102, in get_sheets_service
    return build('sheets', 'v4', credentials=get_credentials())
                                             ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 96, in get_credentials
    return _do_interactive_login()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 50, in _do_interactive_login
    flow = InstalledAppFlow.from_client_secrets_file(CREDENTIALS_FILE, SCOPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './Tokens/credentials.json'
[2025-09-24T00:29:27.331+0000] {taskinstance.py:1242} INFO - Marking task as FAILED. dag_id=WorkOrders, task_id=run_main, run_id=manual__2025-09-24T00:29:22.083401+00:00, execution_date=20250924T002922, start_date=20250924T002923, end_date=20250924T002927
[2025-09-24T00:29:27.361+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-09-24T00:29:27.361+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task run_main ([Errno 2] No such file or directory: './Tokens/credentials.json'; 255)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 327, in run_main
    main()  # executa seu fluxo exatamente como está definido acima
    ^^^^^^
  File "/opt/airflow/dags/Example.py", line 294, in main
    df = filter_existing(df)
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 205, in filter_existing
    svc = get_sheets_service()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 102, in get_sheets_service
    return build('sheets', 'v4', credentials=get_credentials())
                                             ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 96, in get_credentials
    return _do_interactive_login()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Example.py", line 50, in _do_interactive_login
    flow = InstalledAppFlow.from_client_secrets_file(CREDENTIALS_FILE, SCOPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './Tokens/credentials.json'
[2025-09-24T00:29:27.383+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-24T00:29:27.399+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T00:29:27.400+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
